[workspace]
# path of the git-cliff configuration
changelog_config = "cliff.toml"
# update dependencies with `cargo update`
dependencies_update = true
# labels for the release PR
pr_labels = ["release"]
# create GitHub releases for each published crate
git_release_enable = true
# disable running `cargo-semver-checks` until after the first release
semver_check = false
# increase timeout to allow crates.io index propagation between dependent crates
publish_timeout = "10m"
